/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MyurlsImport } from './routes/myurls'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const MyurlsRoute = MyurlsImport.update({
  path: '/myurls',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/myurls': {
      id: '/myurls'
      path: '/myurls'
      fullPath: '/myurls'
      preLoaderRoute: typeof MyurlsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/myurls': typeof MyurlsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/myurls': typeof MyurlsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/myurls': typeof MyurlsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/myurls'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/myurls'
  id: '__root__' | '/' | '/myurls'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MyurlsRoute: typeof MyurlsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MyurlsRoute: MyurlsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/myurls"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/myurls": {
      "filePath": "myurls.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
